### ISSUE TITLE
zip pass

### ISSUE THREAD

**Issue by g0rx** [k8gege/K8tools#1]
zip pass ?

**Comment by k8gege** [comment]
> 
> 
> zip pass ?

k8gege
k8team
K8team

**Comment by qq892371221** [comment]
> > 拉链通行证？
> 
> k8gege
> K8队
> K8队

密码不对呀

**Comment by eppen** [comment]
k8team

**Comment by fnhsoyygy** [comment]
大佬 k8uac_20181125[K8]的解压密码是多少哇，试了一个都不对。。
