### ISSUE TITLE
压缩密码多少啊

### ISSUE THREAD

**Issue by Op7788** [k8gege/K8tools#29]
[https://github.com/k8gege/K8tools/blob/c3a28b9812f7670835a458ea6cf33f5c60b5bf07/K8FTP%E5%AF%86%E7%A0%81%E7%A0%B4%E8%A7%A3%E5%99%A8V2.0_20190301%5BK8%5D.rar](url)

**Comment by k8gege520** [comment]
K8哥哥's BLOG
    http://k8gege.org
