### ISSUE TITLE
关于safe008工具的疑问

### ISSUE THREAD

**Issue by slagman34** [k8gege/K8tools#34]
请问一下作者这个一键加固的软件中隐藏的C盘如何再恢复显示呢，求教

**Comment by k8gege520** [comment]
K8哥哥's BLOG
    http://k8gege.org

**Comment by k8gege520** [comment]
K8哥哥's BLOG
    http://k8gege.org

**Comment by k8gege** [comment]
K8哥哥's BLOG
    http://k8gege.org
